version: '3'

services:
  scrapper:
    build:
      context: scrapper
      dockerfile: Dockerfile
    container_name: scrapper
    environment:
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    environment:
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb
    ports:
      - "80:80"
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
